filetype plugin indent on
syntax on
set complete+=kspell
set colorcolumn=80
set cursorline
set completeopt=menuone,longest
set softtabstop=2
set tabstop=2
set shiftwidth=2
set expandtab
set wildmenu
set shortmess+=c
set showmatch
set showcmd
set showmode
set is
set hls
set mouse=a
set list
set listchars=tab:--,trail:.,eol:¬,extends:>,precedes:<
